MediDent/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('scheduler.urls', namespace='scheduler')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

scheduler/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LoginView

# Custom:
from scheduler.views import schedule, visits_list, client_visits, stats, clients, edit_client, change_visit, \
    new_doctor, fire_doctor

app_name = 'scheduler'

urlpatterns = [
    url(r'^change_visit/(?P<pk>\d+)/$', change_visit, name='change_visit'),

    url(r'^schedule/clients', RedirectView.as_view(url='/clients', permanent=True), {'url': '/clients'}),
    url(r'^schedule/stats', RedirectView.as_view(url='/stats', permanent=True), {'url': '/stats'}),
    url(r'^schedule', schedule, name='schedule'),
    url(r'^visits_list/(?P<first_date>\d+/\d+/\d+)/$', visits_list, name='schedule'),
    url(r'^client_visits/(?P<visit_id>\d+)/$', client_visits, name='schedule'),

    url(r'^stats/clients', RedirectView.as_view(url='/clients', permanent=True), {'url': '/clients'}),
    url(r'^stats/schedule', RedirectView.as_view(url='/schedule', permanent=True), {'url': '/schedule'}),
    url(r'^stats/new_doctor', new_doctor, name='new_doctor'),
    url(r'^stats/fire_doctor/(?P<pk>\d+)/$', fire_doctor, name='fire_doctor'),
    url(r'^stats/', stats, name='stats'),

    url(r'^clients/schedule', RedirectView.as_view(url='/schedule', permanent=True), {'url': '/schedule'}),
    url(r'^clients/stats', RedirectView.as_view(url='/stats', permanent=True), {'url': '/stats'}),
    url(r'^clients/(?P<pk>\d+)/$', edit_client, name='edit_client'),
    url(r'^clients/', clients, name='clients'),

    # url(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^$', schedule, name='schedule'),
    # url(r'^$', LoginView.as_view(template_name='login.html'), name='schedule'),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}MediDent{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}  {% endblock %}

    {% block head_script %}  {% endblock %}
</head>

<body>
{% block body %}
{#    {% block nav_panel %}#}
{#     <nav class="navbar navbar-expand-sm navbar-dark bg-primary sticky-top " style="padding: 0">#}
{#        <div class="container" >#}
{#            <ul class="navbar-nav">#}
{#                 <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'scheduler:schedule' %}">Календар</a>#}
{#                 </li>#}
{#                 <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'scheduler:clients' %}">Список клієнтів</a>#}
{#                 </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'scheduler:stats' %}">Статистика</a>#}
{#                 </li>#}
{#              </ul>#}
{#      </div>#}
{#    </nav>#}
{#    {% endblock %}#}
    {% block content %}{% endblock %}
{% endblock %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% block script %}{% endblock %}

</body>
</html>